from typing import Protocol

from cua.core.schemas import Condition, Step, Target


class Surface(Protocol):
    def navigate(self, url: str) -> None: ...
    def visible(self, target: Target) -> bool: ...
    def execute(self, step: Step, inputs: dict[str, str]) -> str | None: ...
    def check(self, condition: Condition, inputs: dict[str, str]) -> None: ...
    def observe(self) -> dict: ...
    def structural_snapshot(self) -> list: ...
    def set_owner(self, owner: str) -> None: ...
